const customers = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        phone: "123-456-7890",
        street: "123 Main St",
        city: "Orlando",
        state: "FL",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        phone: "987-654-3210",
        street: "456 Elm St",
        city: "Los Angeles",
        state: "CA",
    },
    {
        id: 3,
        name: "Alice Johnson",
        email: "alice@example.com",
        phone: "555-123-4567",
        street: "789 Oak St",
        city: "New York",
        state: "NY",
    },
    {
        id: 4,
        name: "Bob Brown",
        email: "bob@example.com",
        phone: "444-333-2222",
        street: "101 Pine St",
        city: "Chicago",
        state: "IL",
    },
    {
        id: 5,
        name: "Charlie Wilson",
        email: "charlie@example.com",
        phone: "222-111-3333",
        street: "202 Maple Ave",
        city: "Houston",
        state: "TX",
    },
    {
        id: 6,
        name: "Diana Prince",
        email: "diana@example.com",
        phone: "777-888-9999",
        street: "303 Cedar Blvd",
        city: "Seattle",
        state: "WA",
    },
    {
        id: 7,
        name: "Edward Norton",
        email: "edward@example.com",
        phone: "666-555-4444",
        street: "404 Birch Dr",
        city: "Miami",
        state: "FL",
    },
    {
        id: 8,
        name: "Fiona Gallagher",
        email: "fiona@example.com",
        phone: "888-777-6666",
        street: "505 Walnut Lane",
        city: "Phoenix",
        state: "AZ",
    },
    {
        id: 9,
        name: "George Washington",
        email: "george@example.com",
        phone: "333-222-1111",
        street: "606 Ash Ct",
        city: "Philadelphia",
        state: "PA",
    },
    {
        id: 10,
        name: "Hannah Montana",
        email: "hannah@example.com",
        phone: "999-000-1111",
        street: "707 Spruce Way",
        city: "San Diego",
        state: "CA",
    },
];

export default customers;