const products = [
    {
        id: 1,
        name: "Wireless Mouse",
        description: "A smooth and responsive wireless mouse with ergonomic design.",
        price: 29.99,
        created_by: 1,
        created_at: new Date("2023-01-15T14:30:00Z"),
    },
    {
        id: 2,
        name: "Mechanical Keyboard",
        description: "High-performance mechanical keyboard with customizable RGB backlighting.",
        price: 89.99,
        created_by: 2,
        created_at: new Date("2023-01-18T09:15:00Z"),
    },
    {
        id: 3,
        name: "HD Monitor",
        description: "27-inch Full HD monitor with high color accuracy.",
        price: 199.99,
        created_by: 3,
        created_at: new Date("2023-02-05T10:00:00Z"),
    },
    {
        id: 4,
        name: "Laptop Stand",
        description: "Adjustable laptop stand for improved ergonomics.",
        price: 39.99,
        created_by: 1,
        created_at: new Date("2023-02-12T11:30:00Z"),
    },
    {
        id: 5,
        name: "Wireless Charger",
        description: "Fast wireless charging pad compatible with various devices.",
        price: 25.99,
        created_by: 2,
        created_at: new Date("2023-02-20T15:45:00Z"),
    },
    {
        id: 6,
        name: "Bluetooth Headphones",
        description: "Noise-cancelling Bluetooth headphones for immersive sound experience.",
        price: 149.99,
        created_by: 3,
        created_at: new Date("2023-03-01T11:00:00Z"),
    },
    {
        id: 7,
        name: "Webcam",
        description: "High-definition webcam with built-in microphone for clear video calls.",
        price: 59.99,
        created_by: 1,
        created_at: new Date("2023-03-10T09:30:00Z"),
    },
    {
        id: 8,
        name: "Portable SSD",
        description: "1TB portable SSD for fast data transfer and storage.",
        price: 99.99,
        created_by: 2,
        created_at: new Date("2023-03-20T12:00:00Z"),
    },
    {
        id: 9,
        name: "USB-C Hub",
        description: "Multi-port USB-C hub for connecting multiple devices.",
        price: 34.99,
        created_by: 3,
        created_at: new Date("2023-03-25T14:00:00Z"),
    },
    {
        id: 10,
        name: "Gaming Chair",
        description: "Ergonomic gaming chair for maximum comfort during long sessions.",
        price: 199.99,
        created_by: 1,
        created_at: new Date("2023-04-01T15:30:00Z"),
    },
];

export default products;
